name: WetherApp

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      working-directory: ./frontend
      run: yarn
      
    - name: Run the tests
      working-directory: ./frontend
      run: yarn test
      
    - name: Run the lint
      working-directory: ./frontend
      run: yarn lint
